### ISSUE TITLE
I'd like to help improve the docs

### ISSUE THREAD

**Issue by zeke** [rvagg/ghutils#14]
Yo @rvagg I'm really enjoying `ghutils`. Just used it to create [`ghurl`](https://github.com/zeke/ghurl) yesterday.

I'd be happy to open a PR adding some usage examples to the README, and more detail in general about the function arguments and such. Before I do so I want to make sure that this is wanted, and that you're still interested in maintaining this repo.

If you're interested in seeing ghutils improve but don't have the time, I would be happy to help maintain it.

**Comment by ralphtheninja** [comment]
@zeke o/ I also have access to this repo and can release new versions if @rvagg is busy with other stuff. Just saying :)

**Comment by zeke** [comment]
🤘

**Comment by zeke** [comment]
I didn't end up doing it. Sorry! Maybe one day.
