### ISSUE TITLE
move issuesList() function to ghrepos (and rename)

### ISSUE THREAD

**Issue by ralphtheninja** [rvagg/ghutils#4]
Since this function assumes the `/repos` endpoint it should belong to the `ghrepos` module. It should also be renamed to something more generic, like `createRepositoryLister` which knows how to create functions that can list different types under `/repos`, e.g. `'issues'`, `'pulls'` and `'releases'`.

**Comment by ralphtheninja** [comment]
I propose the following:

![20150619_134546](https://cloud.githubusercontent.com/assets/308049/8252832/c97b8108-1689-11e5-9217-ac2536aafd08.jpg)

Where `ghreleases` would be a new module using `ghrepos` so it can list the `'releases'` type.

**Comment by rvagg** [comment]
re `issuesList()` it was actually a lot more complex in the original incarnation when I extracted it, but refactoring `lister()` to be generic like it is has made `issuesList()` almost trivial so I'd actually vote to remove it again and put the functionality back in ghissues and ghpulls separately.

I don't mind the structure you've proposed except that it might be overcomplicated for this stage of the projects unless you really can see functionality that can be extracted into ghrepos.

**Comment by ralphtheninja** [comment]
Sure np. Removing it from `ghutils` and releasing `2.0.0` is a good start and then we can incorporate whatever functionality we need in `ghissues` et. al. after that.

**Comment by ralphtheninja** [comment]
I'll make a PR to `ghrepos` later so you can see what I mean and we can decide if we want that PR or not.
